### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by tylerspencer237** [Eureka22/agar-clone#11]
So I am unable to connect to my server. I got the node_out.js set correctly and works if I launch index.html in firefox but does not work once I put it into my server and go to IP/agar. It shows "If you cannot connect to the servers, check if you have some anti virus or firewall blocking the connection."

**Comment by Eureka22** [comment]
Are you using nginx or Apache to deploy? Check if that support socket...

**Comment by Eureka22** [comment]
Another reason might be some of your action make the server side down, check if your server is still running.

**Comment by tylerspencer237** [comment]
I'm using ngnix and the server is up.

**Comment by tylerspencer237** [comment]
It still says "If you cannot connect to the servers, check if you have some anti virus or firewall blocking the connection." even though it shows the client. Let me repeat again that it works if I open the index.html on my own computer in Firefox

**Comment by Eureka22** [comment]
You can see the console to see if it outputs any useful information. And make sure all the scripts are loaded.

**Comment by tylerspencer237** [comment]
"Make sure all the scripts are loaded?"

**Comment by Eureka22** [comment]
Make sure main_out.js is loaded. Oh as you see the notification about connection, the scripts are already loaded. Never mind. Do you have firewall or something open?

**Comment by tylerspencer237** [comment]
No

**Comment by Eureka22** [comment]
That's weird, if that is the case, I am afraid I cannot help you figure that out. But I will keep this issue open since many other people have already set up the client on there servers, good luck!

**Comment by tylerspencer237** [comment]
You mentioned to load main_out.js, I would of thought it was loaded so how would I go about loading it manually?

**Comment by Eureka22** [comment]
If you are viewing the webpage in a browser, simply go into developer mode and check if all resources are loaded. And check the console output as I mentioned before

**Comment by tylerspencer237** [comment]
The console repeats
"Find US-Fremont" and "TypeError: response is null"

**Comment by tylerspencer237** [comment]
And I found out that it said POST 405 Not Allowed main.php

**Comment by tylerspencer237** [comment]
I'm having trouble trying to solve the 405 not allowed in console

**Comment by m-byte** [comment]
Try changing the method in attemptConnect (main_out.js) from POST to GET. It's currently line 259.
Next, change info.php to info and download m.agar.io/info into the directory.

Another way to solve your problem: install php on your server :wink:

**Comment by Eureka22** [comment]
@m-byte I remember vram's Ogar has something like a master server that can also do the work of i`nfo.php`. But I haven't finish the support for that yet.

**Comment by m-byte** [comment]
@Eureka22 I know, but I think at the moment, it is easier for tylerspencer237 to go one of the routes described in my post

**Comment by Eureka22** [comment]
@m-byte sure.

**Comment by tylerspencer237** [comment]
![ggg](https://cloud.githubusercontent.com/assets/13008477/8392528/5e1c9c70-1ca2-11e5-8b23-8963a303f55e.png)
![ggh](https://cloud.githubusercontent.com/assets/13008477/8392529/5e3dc756-1ca2-11e5-83e0-d7425c21d1d7.PNG)

**Comment by m-byte** [comment]
@tylerspencer237 You did not try what I wrote above. Please do the following things:

 - First, edit `main_out.js`:
   * Line 251 currently reads `wjQuery.ajax("main.php", {`. Change this to `wjQuery.ajax("main", {`
   * Line 259 currently reads `method: "POST",`. Change this to `method: "GET",`

 - Download `m.agar.io/info` and put it into the same directory as `main_out.js`

**Comment by THEDARKK** [comment]
Same , http://i.gyazo.com/caafaa10cc57cc67c5a6fa4d265774ad.png

**Comment by tylerspencer237** [comment]
Okay so I believe I know what happened. I used an A record to direct my domain to my server. When I used my sub-domain, the error message above occurred, however when I used my numerical ip, it somehow worked without any trouble. I am clueless on why the subdomain wouldn't work, however.

**Comment by m-byte** [comment]
@THEDARKK 
1. Not exactly the same. @tylerspencer237 is getting error 405, you are getting a 404.
2. Where did you put the file you downloaded from agar.io?

**Comment by tylerspencer237** [comment]
@m-byte Who are you directing that question to?

**Comment by m-byte** [comment]
@tylerspencer237 Can you try prepending `ws://` to your `CONNECTION_URL` when it is set to your subdomain?

**Comment by m-byte** [comment]
@tylerspencer237 The whole message was directed to THEDARKK.

**Comment by tylerspencer237** [comment]
I javascript:connect("ws://http://connectionURL") and it connects.

**Comment by tylerspencer237** [comment]
What's also weird is that it still logs out 405 main.php even though I changed it to "main" in main_out.js

**Comment by THEDARKK** [comment]
New error : No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by m-byte** [comment]
@tylerspencer237 Did you reload the page in your browser? Please try clearing your cache.
`ws://http://connectionURL` looks wrong. You should only specify one protocol (`ws://connectionURL`)

I just looked through the code. The following lines (285-287) prevent you from using a subdomain:
```
if (/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+$/.test(c) && 5 != +c.split(".")[0]) {
  wsUrl = "ws://" + c;
}
```

Change that to
```
//if (/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+$/.test(c) && 5 != +c.split(".")[0]) {
  wsUrl = "ws://" + c;
//}
```

Now, you should be able to set `CONNECTION_URL` to `your.sub.domain`.

**Comment by m-byte** [comment]
@THEDARKK Are you trying to connect to the official servers? That's prevented on their site and there is no real reason to do anything about that. If you want to use a custom client, just use your own server.

**Comment by tylerspencer237** [comment]
Hm, it still logs 405 errors for main.php

**Comment by m-byte** [comment]
That's really weird. Try this:
In your browser, press F12. Are you using chrome? If so, go to the `Sources` tab and select main_out.js on the left side. Press Ctrl+F and enter `main.php`. Other browsers might have slightly different names for the tab.
If it cannot be found, that would be rally weird. Otherwise, just edit the line in your main_out.js.

**Comment by THEDARKK** [comment]
@m-byte I just want to connect to my server, I have put my ip. but his locks ..

**Comment by m-byte** [comment]
@THEDARKK please install php on your server. Next, go to the agar-clone directory and enter `git reset --hard`. Set `CONNECTION_URL` to the ip and port (`ip:port`) of your ogar server.

**Comment by tylerspencer237** [comment]
It works completely fine now on the subdomain. Thank you for having the patience and time to help. I really appreciate it.

**Comment by m-byte** [comment]
Ok, I'll edit the main_out.js in the repo so that other users won't run into this problem.

**Comment by tylerspencer237** [comment]
It seems that new skins I put into the skins folder don't work. Let's say I put a photo of earth named earth.png, it works fine. If I copy it and rename it to earthtwo.png, it does not work. However, I am able to use a picture of a keyboard, name it earth.png and it works. It seems like it doesn't load any skins with new names

**Comment by Eureka22** [comment]
Thanks@m-byte, you are really helpful

**Comment by m-byte** [comment]
@tylerspencer237 That's because your server is most likely not running php. You can read this page regarding an easy way to check for php support: http://www.cyberciti.biz/faq/how-do-i-test-php-installation-with-a-phpinfo-page/

@Eureka22 You are welcome

**Comment by tylerspencer237** [comment]
I got it now, thank you

**Comment by m-byte** [comment]
Great
