### ISSUE TITLE
Mobile control ideas

### ISSUE THREAD

**Issue by Eureka22** [Eureka22/agar-clone#12]
On-screen Joystick or gravity control, which do you think is better for this game?

**Comment by m-byte** [comment]
I think a joystick would get in the way on the screen of a smaller phone. Something I was thinking about: Why not let the player choose on the main screen?

**Comment by Jackster35** [comment]
The ability to choose at the menu screen would be awesome. Every player has their own style of gaming.

**Comment by Eureka22** [comment]
btw a joystick control will be something like https://github.com/Eureka22/TinkerControllerWebApp.git . It is such that you start touch the screen, and that becomes a joystick, then you drag. If you stop touching, the joystick will disappear. 

I would prefer setting the joystick as default and we allow players to choose gravity control.

**Comment by m-byte** [comment]
Sounds good‎ :+1:                                                                                                                                                                                                                Von: Fei XiaGesendet: Samstag, 27. Juni 2015 04:26An: Eureka22/agar-cloneAntwort an: Eureka22/agar-cloneCc: m-byteBetreff: Re: [agar-clone] Mobile control ideas (#12)btw a joystick control will be something like https://github.com/Eureka22/TinkerControllerWebApp.git . It is such that you start touch the screen, and that becomes a joystick, then you drag. If you stop touching, the joystick will disappear. 

I would prefer setting the joystick as default and we allow players to choose gravity control.

—Reply to this email directly or view it on GitHub.
