### ISSUE TITLE
Chat super big

### ISSUE THREAD

**Issue by Jackster35** [Eureka22/agar-clone#17]
Ever since the latest push of main_out.js, the chat has been super huge

Is there a way of using the old configuration as that was perfect? Thank man!

http://i.imgur.com/XFzifMa.png

**Comment by Jackster35** [comment]
I've worked out my own fix for it, but it would still be useful to fix it for others. :)

**Comment by Eureka22** [comment]
Got an exam tomorrow, will fix it later, should not be too hard.

**Comment by m-byte** [comment]
@Jackster35 Would you care to share how you fixed it? Would be a lot easier then us tracking a bug down you already fixed.

**Comment by Eureka22** [comment]
I think it is because I hard-coded the chat board width.

**Comment by Jackster35** [comment]
I basically reverted to the old configuration. If you like, I could push my changes and you could merge?

**Comment by Eureka22** [comment]
No rush :) we will investigate later, btw what it the resolution of your screen?

**Comment by Jackster35** [comment]
I run at 1920x1080 sir :)

**Comment by Eureka22** [comment]
Maybe you can change the scaleFactor to 1 in drawChatBoard function and it will be the same as old version. Originally I would like it to look better on computer and mobile phone but the solution is not so good, I will try another one later :)

**Comment by Eureka22** [comment]
fixed
