### ISSUE TITLE
Skin Gallery

### ISSUE THREAD

**Issue by tylerspencer237** [Eureka22/agar-clone#19]
When I go into my gallery, all the pictures show up as white and don't load

**Comment by Eureka22** [comment]
Can you look at the console? Maybe lack of some dependencies.  You will need `php5-gd` to make it work. As it is not a core function in agar-clone, we didn't write it in readme. 

You can look at [this](http://lifeonubuntu.com/how-to-install-php-gd2-library-on-ubuntu/) about how to install GD2 library.
