### ISSUE TITLE
Crash when eating virus

### ISSUE THREAD

**Issue by Jackster35** [Eureka22/agar-clone#21]
Hey, I've just updated our client to the latest and found that sometimes when eating a virus, your client will crash.

We test around 300-400 mass

**Comment by Eureka22** [comment]
Thank you, I will investigate. BTW, when you say eat, you mean eat virus or collide into virus and burst?

**Comment by Jackster35** [comment]
Both cause it I'm being told

**Comment by Eureka22** [comment]
@Jackster35 Can you provide more details? I just tested but didn't have the same issue. And crush when eating virus is more like a server-side problem?

Can you describe the crush a little bit more and tell me what version of server are you using. Thanks.

**Comment by Jackster35** [comment]
It would seem your latest push has fixed this. I believe the user reporting it is on an old version of the code. Thank you anyways, appreciate it man :)

**Comment by Eureka22** [comment]
@Jackster35 The least I could do :)
