### ISSUE TITLE
Bigger menu for mobile users

### ISSUE THREAD

**Issue by Jackster35** [Eureka22/agar-clone#24]
Our site uses a larger menu, which looks to break the mobile version as it seems to be preset for the default one. Could you direct me where to change the dimensions of could you implement a way of auto detection?

Either would be awesome, thanks Eureka22 :)

**Comment by Eureka22** [comment]
What about make it scrollable? Or resize accordingly(that will make the text smaller)

**Comment by Jackster35** [comment]
Either one would do the trick, any idea how I'd do that?

**Comment by Eureka22** [comment]
fixed
