### ISSUE TITLE
Hide chat?

### ISSUE THREAD

**Issue by Jackster35** [Eureka22/agar-clone#25]
Would be a way of possibly hiding the chat with a button? :)

**Comment by m-byte** [comment]
Especially on cell phones, it's probably easier to have an option on the welcome screen.                                                                                                                                                                                                                                                                                                                                        Gesendet von meinem BlackBerry 10-Smartphone.                                                                                                                                                                                                                Von: Jackster35Gesendet: Montag, 29. Juni 2015 16:59An: Eureka22/agar-cloneAntwort an: Eureka22/agar-cloneBetreff: [agar-clone] Hide chat? (#25)Would be a way of possibly hiding the chat with a button? :)

—Reply to this email directly or view it on GitHub.

**Comment by vram4** [comment]
A checkbox would be pretty easy to implement

**Comment by Jackster35** [comment]
Yes, I'm sure it wouldn't be too hard to implement. :)

**Comment by Jackster35** [comment]
I tried doing it my self but I was just having issues with getting it to work on the main_out.js
