### ISSUE TITLE
Big error!

### ISSUE THREAD

**Issue by Jackster35** [Eureka22/agar-clone#27]
I'm running on the latest version and when you press play, the game just won't work. It also had issues where nothing worked. If you could drop your email, I'll show you a link to what I'm seeing.

**Comment by m-byte** [comment]
Irgendwer2@gmail.com

**Comment by Jackster35** [comment]
Sent.

**Comment by m-byte** [comment]
In your config, there is only the server ###.95.##.29:1501 hardcoded into your main.js. This server seems to be unavailable. Therefore, you are unable to connect to anything.

**Comment by Jackster35** [comment]
http://i.imgur.com/P7UBhy4.png

Is actually our hard-coded config.

**Comment by vram4** [comment]
Wait, what do you mean by the game not working? Like you can see other cells but not spawn? or just a blank screen?

**Comment by Jackster35** [comment]
It's now gone to a blank screen, I sent you a link to it on Skype vram4

**Comment by m-byte** [comment]
Actually, I was wrong. It selects different servers, however, all of those seem to not be working.
So I tried to connect with the official client and it did not work on any one of them.

**Comment by Jackster35** [comment]
Go to the site without /new/ and you'll see they all work.

**Comment by m-byte** [comment]
Do you have some kind of geo-lock installed? They don't work from Germany (or at least not from my ip).

**Comment by Jackster35** [comment]
Nope haha, I'm not named Zeach ;)
