### ISSUE TITLE
Fail to respawn after you die

### ISSUE THREAD

**Issue by Jackster35** [Eureka22/agar-clone#31]
Sometimes when you die, if you press play again you'll hang on an empty screen.

**Comment by vram4** [comment]
Its a server bug, the client does spawn, but it spawns in another player and gets eaten immediately, which results in the client seeing an empty screen.

**Comment by Jackster35** [comment]
Ah right, do you think there will be a fix due?

**Comment by vram4** [comment]
Probably, currently im working on trying to solve an issue with the connection limit

**Comment by Jackster35** [comment]
Ah cool man! Take your time, always appreciate your help, you're awesome! :)

**Comment by vram4** [comment]
Fixed in forairan/Ogar@2355a553ac128e0da5371087ce9c0686e8224528 You now spawn from food. So unless there is no food on the map, there shouldnt be problems.
