### ISSUE TITLE
chat is not working

### ISSUE THREAD

**Issue by deviant13** [Eureka22/agar-clone#32]
can you please fix the chat window? when i type anything and press enter, nothing happens

**Comment by Eureka22** [comment]
Make sure you use the right server version. It works with my fork of Ogar as well as m-byte's repo Cigar. I

**Comment by vram4** [comment]
Not a bug, standard Ogar does not have chat support, use Eureka22/Ogar instead.

**Comment by Eureka22** [comment]
by the way, I am busy these days so I don't have time to update my code, if you want to get the latest code you can clone my repo and then pull from vram4's repo.

**Comment by m-byte** [comment]
@deviant13 or use Cigar. It currently is consists of agar-clone bundled with the customized version of Ogar.

**Comment by deviant13** [comment]
i'm using windows 7, is this the issue?

**Comment by Eureka22** [comment]
@deviant13 Probably, because the binary executable file is not updated, try to use `node` to run my code instead.

**Comment by Eureka22** [comment]
@deviant13 And btw I encourage you to use Cigar.

**Comment by deviant13** [comment]
hello, thanks for the help. can you please kindly make a small detailed tutorial on how to use node and commands etc. thanks!

**Comment by Eureka22** [comment]
@deviant13 Sure. I don't use windows but you can look at this: http://stackoverflow.com/questions/15331440/how-can-i-use-nodejs-with-windows-7

**Comment by deviant13** [comment]
should i just use vmware and install linux os?

**Comment by m-byte** [comment]
@deviant13 I will compile Cigar for Windows. Should be done in an hour or so. Just have to get my laptop.

**Comment by deviant13** [comment]
heeeey m-byte thanks! you're the life saver :+1:

**Comment by m-byte** [comment]
@deviant13 There is now an exe available at https://github.com/m-byte/Cigar

**Comment by deviant13** [comment]
wow thank you so much.
