### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by techpulse** [Eureka22/agar-clone#33]
http://i.imgur.com/ZxQK6xC.gif

**Comment by Eureka22** [comment]
Use correct server version.  try my fork of Ogar or use Cigar

**Comment by techpulse** [comment]
Does your 'fork' of ogar also contain the latest fixes that vram made?

**Comment by techpulse** [comment]
you should add a standalone chat, that i can run instead of running it with ogar or cigar :) ?

**Comment by Eureka22** [comment]
No. It's not updated for a long time. You need to fix that your self.

**Comment by Eureka22** [comment]
You can write a standalone chat using socket, as the rendering function is already implemented it should not be hard :)

**Comment by techpulse** [comment]
no i don't code javascript, and ogar has been updated recently with fixes
