### ISSUE TITLE
This is possible?

### ISSUE THREAD

**Issue by mafiakb** [Eureka22/agar-clone#34]
Hi, one question.

Is possible add border at virus or cell?

Image.

![border](https://cloud.githubusercontent.com/assets/12769609/8640245/5426bff4-28b7-11e5-96f0-6085f3a280e7.png)

**Comment by m-byte** [comment]
I am not exactly sure what you are trying to accomplish. Do you want the border to be thicker? And if so, do you want it the same width for every user?

**Comment by mafiakb** [comment]
Yes, look border have line u can add?

**Comment by m-byte** [comment]
It is set to 10px in https://github.com/Eureka22/agar-clone/blob/master/main_out.js#L1428
So it should already be there.

**Comment by mafiakb** [comment]
U best nice border, but u can add line? example:

![border2](https://cloud.githubusercontent.com/assets/12769609/8640497/b3e85368-28c0-11e5-8185-7bdd142685bb.png)

**Comment by Eureka22** [comment]
@mafiakb Why do you want to add line? It seems that it does not look any better.

**Comment by mafiakb** [comment]
@Eureka22 to make it look different and make changes.

**Comment by mafiakb** [comment]
is possible add line?

**Comment by m-byte** [comment]
It's sssomething you'll have to do after downloading agar-client.

**Comment by vram4** [comment]
@Eureka22 He wants to avoid copyright issues :p
