### ISSUE TITLE
How to enable the chat?

### ISSUE THREAD

**Issue by FilipeGNU** [Eureka22/agar-clone#36]
I have a agario server.

I use the following server : https://github.com/forairan/Ogar

And use the client of you , but can not make the chat function , he even appears but when I type something not working .

Follow the link from my server : http://agar.labfree.com.br/

**Comment by vram4** [comment]
Use https://github.com/m-byte/Cigar for chat support.

**Comment by FilipeGNU** [comment]
Tankyou very much!
Sorry for my bad english...
