### ISSUE TITLE
I'm trying to connect agar.io original server

### ISSUE THREAD

**Issue by Ganggroid** [Eureka22/agar-clone#37]
![2015-07-15 19 21 53](https://cloud.githubusercontent.com/assets/5188404/8696399/f7e117f4-2b26-11e5-9cdf-b7a51b5de26d.PNG)

i have an error!
what problem??

**Comment by m-byte** [comment]
Connecting to the official server is a feature we do not support. This client does not offer any additional features when connected to official servers, so there is no point in us supporting this.

https://github.com/Eureka22/agar-clone/#faq
