### ISSUE TITLE
failed: Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by Ganggroid** [Eureka22/agar-clone#38]
failed: Error during WebSocket handshake: Unexpected response code: 400
![2015-07-15 19 21 53](https://cloud.githubusercontent.com/assets/5188404/8697452/0697ffac-2b30-11e5-9052-3e076450eed3.PNG)
How to fix this error?

**Comment by m-byte** [comment]
@Ganggroid The problem is on the server side. There is no way to fix this in agar-clone.
In your last issue you wrote that this IP belongs to an official server. We don't support the official server with this client. If you want to use the official server, use the official client.
