### ISSUE TITLE
so, I mean..

### ISSUE THREAD

**Issue by Ganggroid** [Eureka22/agar-clone#39]
I want answer about it.
I'm using Original Agar.io client.
I copy that, and i accpet at my server.
But It has error
![2015-07-15 19 21 53](https://cloud.githubusercontent.com/assets/5188404/8698857/443ff7b8-2b3c-11e5-984b-d68cd74d58a3.PNG)
Uh.. I want to listen about how to Fix this error in server.
My server is using Apache2.
Thanks.

**Comment by m-byte** [comment]
Please use agar-clone (the client you are writing issues for although you are not using it), or stop writing issues here. We don't support the official client or server.
