### ISSUE TITLE
How to add "Teams" or "Experimental" to work

### ISSUE THREAD

**Issue by NikoCodex** [Eureka22/agar-clone#46]
I keep clicking them however it doesn't seem to work, it just sends me into the same server.
What do i type in the master console to get it working?
I mean can someone explain to me how to do it? This has confused me...

**Comment by NikoCodex** [comment]
I'm using Cigar by the way.

**Comment by mafiakb** [comment]
@NikoCodex need modify client

**Comment by NikoCodex** [comment]
Here is my website http://blobeatblob.cf/ and how do i modify the client?
I got the problem that i need to open another port with the same source with the gamemode, but how do i make it connect?
Thanks.

**Comment by mafiakb** [comment]
Modify index.html, main_out and add js.

index.html modify:

<script src="js/servers.js"></script>
</head>
////////
<select id="region" class="form-control" onchange="setRegion($('#region').val());" required>
<option value="0" selected>Server #1</option>
<option value="1">Server #2</option>
<option value="2">Server #3</option>
//////
<script type="text/javascript">
           var domain = "localhost";
           var host = "ip:port";
           var pvp_title = "PVP";
           var KEY_ENTER = 13;
           var skor_name = "SKOR";      
</script>
</body>
///////
main_out.js

    function attemptConnection() {
                wsConnect("ws://" + host);)
    }

///////
 function wsConnect(wsUrl) {
        if (ws) {
            ws.onopen = null;
            ws.onmessage = null;
            ws.onclose = null;
            try {
                ws.close()
            } catch (b) {
            }
            ws = null
        }
        nodesOnScreen = [];
        playerCells = [];
        nodes = {};
        nodelist = [];
        Cells = [];
        leaderBoard = [];
        mainCanvas = teamScores = null;
        userScore = 0;
        console.log("Connecting to " + wsUrl);
        ws = new WebSocket(wsUrl);
        ws.binaryType = "arraybuffer";
        ws.onopen = onWsOpen;
        ws.onmessage = onWsMessage;
        ws.onclose = onWsClose;
        ws.onerror = function () {
            console.log("socket error");
        }
    }

//////

Create new servers.js

    function setRegion(mod){
        if(mod == 0){
            host = "ip:port";
            setGameMode(0);
        }else if(mod == 1){
            host = "ip:port";
            setGameMode(1);
        }else if(mod == 2){
            host = "ip:port";
            //host = "ip:port";
            setGameMode(2);
        }
    }

remember to backup.

**Comment by mafiakb** [comment]
@NikoCodex use this guide:

http://pastebin.com/0Xa5sHum

**Comment by NikoCodex** [comment]
Doesn't work http://blobeatblob.cf/
I honestly doubt this is the way you do it, any other way, i think that it needs to request the ip and port for the gamemodes in main.php

**Comment by mafiakb** [comment]
@NikoCodex yes work men =/ but np

**Comment by NikoCodex** [comment]
It DOESNT work.

**Comment by mafiakb** [comment]
<script type="text/javascript">
           var domain = "localhost";
           var host = "ip:port";
           var pvp_title = "PVP";
           var KEY_ENTER = 13;
           var skor_name = "SKOR";      
</script>

**Comment by NikoCodex** [comment]
I edited it, now i reverted to old settings, i'm trying to use the same method Agar.io or Agario.biz uses. This just...

**Comment by mafiakb** [comment]
i clone agar.io or agario.biz how much? :3

**Comment by NikoCodex** [comment]
Agario.biz uses this agar clone and they use a different method of gamemodes.
They use main.php to retrieve the new IP:PORT when the gamemode is chosen, i'm looking for that method, i don't want you to copy anything.

**Comment by mafiakb** [comment]
agario.biz no use main.php. look 

				<select class="btn btn-primary" id='serverim' onchange="setserver($(this).val());">
					<option value='146.148.51.129:443'>FFA 1</option>
					<option value='130.211.89.246:443'>FFA 2</option>
					<option value='37.123.102.149:443'>FFA 3</option>
					<option value='146.148.51.129:4440'>FFA 4</option>
					<option value='130.211.89.246:1453'>Team</option>
					<option value='130.211.89.246:1454'>Exper.</option>
				</select>

**Comment by NikoCodex** [comment]
Interesting, can you help me implement it?

**Comment by m-byte** [comment]
As I wrote over at https://github.com/m-byte/Cigar/issues/26, there is an easier solution: edit masterserver.ini and define your custom regions.

**Comment by NikoCodex** [comment]
As i wrote there, there is an even easier solution
Sorry to challange your intellect, but there's a way without regions.
Add this to the main_out.js
Handle.setserver = function (arg) {
        if (arg != gameMode) {
             CONNECTION_URL = arg;
            gameMode = arg;
            showConnecting();
        }
    };
In index, change
onchange="setGameMode($(this).val());"
to
onchange="setserver($(this).val());"
Now update your options:
  <option value='IP:PORT'>FFA</option>
                    <option value='IP:PORT'>Teams</option>
                    <option value='IP:PORT'>Experimental</option>
Thanks for nothing.

**Comment by m-byte** [comment]
First of all, there is no need to be rude. All the developers working on these projects do so in their free time. Same goes for answering issues.

Given that you apparently expected mafiakb to do all the work for you, it appeared fair to assume that you were searching for an easy solution. That's exactly what I gave you.

If you think you are smarter than everyone working on this project, feel free to fix issues you find by forking, editing code and submitting merge requests.

**Comment by NikoCodex** [comment]
Unfortunately i am not a developer of Javascript or Node JS.
