### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by matrixreal** [Eureka22/agar-clone#47]
hi,
is there another website to test the game i have tested this http://eureland.me
is there another ?
thanks

**Comment by matrixreal** [comment]
@Eureka22 
@m-byte 
why game is lagging much on mobile ? http://eureland.me ?
thanks for reply

**Comment by matrixreal** [comment]
this website is using an ogar server ?

**Comment by m-byte** [comment]
It is using our modified Ogar. You could think of it as Cigar 0.1.

**Comment by helma27** [comment]
you can test mine here, http://agarindo.pw

**Comment by matrixreal** [comment]
@helma27 
how you done it friend ?
now my server is accessible via 88.167.14.2
but as you can see i got always connecting issue from public internet
on local when i tape 88.167.14.2 it work
any solution ?

**Comment by Eureka22** [comment]
@helma27 I am glad you made that.

**Comment by matrixreal** [comment]
@helma27 
how you add music ? and modify the game title ? what is the file to change ?
thanks for reply

**Comment by m-byte** [comment]
@matrixreal Edit index.html

**Comment by matrixreal** [comment]
@m-byte but there is no index.html ???
https://github.com/m-byte/Cigar
it was deleted no ?

**Comment by m-byte** [comment]
You wrote the issue for the wrong project. In agar-clone, it is index.html, for Cigar, use game.hbs. As i wrote in the commit https://github.com/m-byte/Cigar/commit/a4e53eb51ab08ae0a6191b595a9d1b3a9ce3b2bd, index.html is not used in Cigar and only caused confusion. For changing the title, use https://github.com/m-byte/Cigar/blob/master/server/web/routes/index.js

**Comment by helma27** [comment]
@Eureka22 thank you for your great works! I love your works :) But some people has some issue in some browser, like blank page or You must press ESC to get the menu and play it,, Mostly occur in Mozilla Firefox browsers..

@matrixreal right now i'm using multiple server, one in Singapore (@forairan Ogar Server)
Second US Server (@forairan Ogar Server)
And Amsterdam Server that i used in mode FFA, Teams, Rainbow, Last Man or Hunger Games, and Team Experimental,in this case, i use @m-byte Cigar Server, it support multi mode or port server in one VPS~
For Custom change in game  like music, game title, etc, Just edit the index.html :)
For future update in my Agar-client, i will add User System or Login system that use MySQL and PHP :D

**Comment by matrixreal** [comment]
@m-byte i'm sorry 
thanks a lot
great project
we love you here in France
but there is only small issue with mobile lagging
hope you will it soon

**Comment by m-byte** [comment]
@matrixreal just reread my post and it sounds pretty harsh didn't mean for it to sound that way. No need to be sorry ;)

**Comment by matrixreal** [comment]
@helma27 yes you got reason
there is also white page in safari browser
is there a way to disable chat and enable smooth render automatically (by default)

**Comment by m-byte** [comment]
@matrixreal Currently I am working on a complete rewrite of the client. It will be based on pixi.js. It will also be more tightly integrated with Cigar (you'll be able to configure the client from the server config). After that, I'll continue my work on user management and then, the next goal is having the ability to use multiple separate servers.

**Comment by matrixreal** [comment]
@m-byte wow
i told you you are magic ...
we are waiting :dancer: 
last issue about mobile lagging , what do you think ?

**Comment by m-byte** [comment]
At the moment, you can disable the chat using the options.

**Comment by matrixreal** [comment]
@m-byte 
thats okay thanks
i disable chat and enable smooth render but the game still lagging ?
