### ISSUE TITLE
mobile lagg issue

### ISSUE THREAD

**Issue by matrixreal** [Eureka22/agar-clone#48]
hi all
can you tel me why it lag a lot on mobile ? (i have good internet)
also can you ajust joystick controle on mobile like original agar.io
thanks

**Comment by Eureka22** [comment]
The server is in SF and that is the only problem. If you do a local host then this problem goes away. Close this issue because it has nothing to do with this repo.

**Comment by matrixreal** [comment]
can i do a localhost on mobile ? or it download it automatically since lunch on mobile browser ? confuseD ?

**Comment by Eureka22** [comment]
Run a server on your localhost, connect your phone to the same LAN as your computer. Then test it on your mobile browser.

**Comment by matrixreal** [comment]
i'm putting game here 88.167.14.2
