### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by tylerspencer237** [Eureka22/agar-clone#7]
Could you please put the commands to put into a server? I have LEMP installed. For ubuntu/debian.

**Comment by Eureka22** [comment]
Suppose your nginx document root is at `/var/www`, simply do the following:

```bash
cd /var/www
git clone https://github.com/Eureka22/agar-clone.git agar
chmod 777 agar/skins
```

Then visit http://your-server-ip/agar/ it should work.

**Comment by Eureka22** [comment]
Oh and don't forget to replace the `CONNECTION_URL` with your own ip and port in `main_out.js`
