### ISSUE TITLE
Call for test for in game chat. 

### ISSUE THREAD

**Issue by Eureka22** [Eureka22/agar-clone#8]
Just finish the test feature, it is in `web-server` branch. It works with my server side https://github.com/Eureka22/Ogar.  I will really appreciate it if you guys can help me test that. No other configurations required.

It looks like this: 
![image](https://cloud.githubusercontent.com/assets/5158896/8327532/c41e94fa-1a9b-11e5-87cc-f42b5f6ef2df.png)

**Comment by m-byte** [comment]
Don't forget to document your protocol extension ;)

**Comment by Eureka22** [comment]
yes I did :)

**Comment by m-byte** [comment]
I think we should reduce the overhead of the chat function a bit more. Client to server, only the message should be needed. Also, I would change the order of the s2c package as follows:
r(uint8); g(uint8); b(uint8); name, terminated by '\0'; message, terminated by '\0'
That way, it would be more in line with other packages.

Btw: The node-id (I would probably send it after b and before name) might be useful as well. That way, messages could be filtered by proximity.

**Comment by m-byte** [comment]
Something I forgot to write in my last messages: good job!

**Comment by m-byte** [comment]
I just sent you a merge request for the server. As I wrote there, I will adjust agar-clone accordingly either today or tomorrow.

As a user usually has one or more node-ids, I can't think of an easy way to pick the best one to send. Therefore, I am using bits 2, 4, and 8 of the flags for additional offsets. This way, it can easily be added once someone feels the need to do this client side and still won't break support of other clients.

**Comment by m-byte** [comment]
Sent you both merge request.

**Comment by Eureka22** [comment]
@m-byte just fixed a bug.

**Comment by m-byte** [comment]
Oh :flushed: I just wrote the code down and apparently forgot to do a proper test afterwards.

**Comment by Eureka22** [comment]
never mind, it works fine now :)
